# SPDX-License-Identifier: Apache-2.0
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/release.yml@72ffc70b5253c30afd47b06e81eff3f9b08c04c8
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    with:
      image-name: "rune-ui"
      notify-charts: true
    secrets:
      RUNE_CHARTS_BOT_TOKEN: ${{ secrets.RUNE_CHARTS_BOT_TOKEN }}
